export const STUDENT = {
  firstName: "Riya",
  lastName: "Mehta",
  email: "riya.mehta45@college.edu",
  phone: "+91 9123456789",
  gender: "Female",
  dob: "2002-09-18",
  address: "47, Lajpat Nagar, Block B",
  city: "New Delhi",
  state: "Delhi",
  country: "India",
  zip: "110024",
  enrollmentNo: "CS21B045",
  course: "B.Tech",
  branch: "Computer Science",
  semester: "5th",
  section: "A",
  batch: "2021–2025",
  rollNumber: "CS21B045",
  college: "Delhi Technological University",
  admissionYear: "2021",
  graduationYear: "2025",
  guardianName: "Suresh Mehta",
  guardianRelation: "Father",
  guardianPhone: "+91 9876501234",
  guardianEmail: "suresh.mehta@gmail.com",
  username: "riya.mehta",
  registrationDate: "August 10, 2021",
  lastLogin: "Today, 10:02 AM",
  accountStatus: "Active",
  emailVerified: true,
  phoneVerified: true,
  attendance: 92,
  attended: 110,
  missed: 14,
  streak: 10,
  longestStreak: 14,
};

export const ACTIVITY_TIMELINE = [
  {
    icon: "✅",
    text: "Marked present in DBMS (GA-101)",
    time: "10:03 AM",
    date: "Today",
  },
  {
    icon: "📍",
    text: "Location verified for OS session",
    time: "11:14 AM",
    date: "Today",
  },
  {
    icon: "🔳",
    text: "QR code scanned for Web Dev Lab",
    time: "2:05 PM",
    date: "Yesterday",
  },
  {
    icon: "👤",
    text: "Profile information updated",
    time: "6:30 PM",
    date: "Jun 28",
  },
  {
    icon: "🔒",
    text: "Password changed successfully",
    time: "9:00 AM",
    date: "Jun 25",
  },
  {
    icon: "✅",
    text: "Marked present in Data Structures",
    time: "9:01 AM",
    date: "Jun 24",
  },
];

export const ACHIEVEMENTS = [
  {
    emoji: "💯",
    title: "100% in DSA",
    desc: "Perfect attendance in Data Structures.",
    earned: true,
  },
  {
    emoji: "🔥",
    title: "10-Day Streak",
    desc: "Attended 10 consecutive sessions.",
    earned: true,
  },
  {
    emoji: "⭐",
    title: "Perfect Week",
    desc: "All sessions attended this week.",
    earned: true,
  },
  {
    emoji: "🎓",
    title: "Semester Excellence",
    desc: "Above 90% overall this semester.",
    earned: false,
  },
];
