export const NOTIFICATIONS = [
  {
    id: "N001",
    type: "attendance",
    icon: "✅",
    title: "Attendance Submitted",
    desc: "Rahul Sharma submitted attendance for DBMS session GA-101.",
    time: "2m ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "N002",
    type: "absent",
    icon: "🔴",
    title: "Student Absent Alert",
    desc: "Karan Patel missed the Operating Systems session. 3rd consecutive absence.",
    time: "8m ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "N003",
    type: "late",
    icon: "🟡",
    title: "Late Arrival Detected",
    desc: "Anjali Nair joined the DBMS session 12 minutes after the window closed.",
    time: "15m ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "N004",
    type: "session",
    icon: "🚀",
    title: "Session Started",
    desc: "Attendance session GA-103 for Computer Networks has gone live.",
    time: "22m ago",
    date: "Today",
    read: false,
    category: "Sessions",
  },
  {
    id: "N005",
    type: "session",
    icon: "🏁",
    title: "Session Ended",
    desc: "Session GA-101 for DBMS has been automatically closed. 56/60 students present.",
    time: "1h ago",
    date: "Today",
    read: true,
    category: "Sessions",
  },
  {
    id: "N006",
    type: "student",
    icon: "👤",
    title: "New Student Joined",
    desc: "Vikram Joshi registered and joined CSE-A for the 5th Semester.",
    time: "2h ago",
    date: "Today",
    read: false,
    category: "Students",
  },
  {
    id: "N007",
    type: "qr",
    icon: "📵",
    title: "QR Scan Failed",
    desc: "Tanya Roy attempted to scan an expired QR code for session GA-102.",
    time: "3h ago",
    date: "Today",
    read: true,
    category: "Attendance",
  },
  {
    id: "N008",
    type: "location",
    icon: "📍",
    title: "Location Verification Failed",
    desc: "Arjun Mehta was outside the allowed radius (82m vs 50m allowed) for session GA-101.",
    time: "3h ago",
    date: "Today",
    read: true,
    category: "Attendance",
  },
  {
    id: "N009",
    type: "system",
    icon: "🔧",
    title: "System Update",
    desc: "GeoAttend has been updated to v2.4.1. New QR encryption algorithm is now active.",
    time: "5h ago",
    date: "Today",
    read: true,
    category: "System",
  },
  {
    id: "N010",
    type: "announcement",
    icon: "📢",
    title: "New Announcement",
    desc: "Department head has scheduled a faculty meeting on July 5th at 10 AM.",
    time: "6h ago",
    date: "Today",
    read: false,
    category: "Announcements",
  },
  {
    id: "N011",
    type: "attendance",
    icon: "✅",
    title: "Attendance Submitted",
    desc: "Priya Singh submitted attendance for Software Engineering session GA-104.",
    time: "1d ago",
    date: "Yesterday",
    read: true,
    category: "Attendance",
  },
  {
    id: "N012",
    type: "absent",
    icon: "🔴",
    title: "Student Absent Alert",
    desc: "Tanya Roy missed the Computer Networks session for the 2nd time this week.",
    time: "1d ago",
    date: "Yesterday",
    read: true,
    category: "Attendance",
  },
  {
    id: "N013",
    type: "student",
    icon: "📋",
    title: "Student Request",
    desc: "Sneha Iyer has requested manual attendance marking for June 29 due to medical reasons.",
    time: "1d ago",
    date: "Yesterday",
    read: false,
    category: "Students",
  },
  {
    id: "N014",
    type: "session",
    icon: "🚀",
    title: "Session Created",
    desc: "You successfully created attendance session GA-105 for Web Development lab.",
    time: "1d ago",
    date: "Yesterday",
    read: true,
    category: "Sessions",
  },
  {
    id: "N015",
    type: "announcement",
    icon: "📢",
    title: "Attendance Policy Update",
    desc: "Minimum attendance requirement has been revised to 75% from next semester.",
    time: "2d ago",
    date: "Jun 28",
    read: true,
    category: "Announcements",
  },
  {
    id: "N016",
    type: "system",
    icon: "🔔",
    title: "Weekly Report Ready",
    desc: "Your weekly attendance summary report for June 23–29 is now available for download.",
    time: "2d ago",
    date: "Jun 28",
    read: true,
    category: "System",
  },
  {
    id: "N017",
    type: "qr",
    icon: "🔳",
    title: "QR Code Refreshed",
    desc: "QR code for session GA-101 was automatically refreshed after the 60-second expiry.",
    time: "2d ago",
    date: "Jun 28",
    read: true,
    category: "Sessions",
  },
  {
    id: "N018",
    type: "late",
    icon: "🟡",
    title: "Late Arrival Detected",
    desc: "Aman Gupta joined Software Engineering session 8 minutes after the allowed window.",
    time: "3d ago",
    date: "Jun 27",
    read: true,
    category: "Attendance",
  },
  {
    id: "N019",
    type: "attendance",
    icon: "📊",
    title: "Low Attendance Warning",
    desc: "CSE-B attendance for Software Engineering has dropped to 68% this month.",
    time: "3d ago",
    date: "Jun 27",
    read: false,
    category: "Attendance",
  },
  {
    id: "N020",
    type: "student",
    icon: "🏆",
    title: "Perfect Attendance Milestone",
    desc: "Rahul Sharma has achieved 100% attendance for the month of June. Consider recognizing them!",
    time: "3d ago",
    date: "Jun 27",
    read: true,
    category: "Students",
  },
  {
    id: "N021",
    type: "system",
    icon: "🛡️",
    title: "Security Alert",
    desc: "Multiple failed QR scan attempts detected from the same device in session GA-103.",
    time: "4d ago",
    date: "Jun 26",
    read: false,
    category: "System",
  },
  {
    id: "N022",
    type: "session",
    icon: "🏁",
    title: "Session Ended",
    desc: "Session GA-102 for Operating Systems ended. Attendance: 52/55 students present.",
    time: "4d ago",
    date: "Jun 26",
    read: true,
    category: "Sessions",
  },
  {
    id: "N023",
    type: "announcement",
    icon: "🎓",
    title: "End Semester Exam Schedule",
    desc: "End semester examination schedule for November 2026 has been announced.",
    time: "5d ago",
    date: "Jun 25",
    read: true,
    category: "Announcements",
  },
  {
    id: "N024",
    type: "location",
    icon: "📍",
    title: "Location Spoof Detected",
    desc: "Possible location spoofing detected for Riya Verma during DBMS session GA-101. Marked as suspicious.",
    time: "5d ago",
    date: "Jun 25",
    read: false,
    category: "Attendance",
  },
  {
    id: "N025",
    type: "student",
    icon: "📧",
    title: "Student Feedback Received",
    desc: "Meera Kumar submitted feedback for the QR attendance system — rated 4.5/5.",
    time: "6d ago",
    date: "Jun 24",
    read: true,
    category: "Students",
  },
];

export const CATEGORY_FILTERS = [
  "All",
  "Unread",
  "Read",
  "Attendance",
  "Sessions",
  "Students",
  "Announcements",
  "System",
];
