export const STUDENT_NOTIFICATIONS = [
  {
    id: "SN001",
    type: "attendance",
    icon: "✅",
    title: "Attendance Marked Successfully",
    desc: "Your attendance for DBMS (GA-101) has been verified using QR + Location.",
    time: "5m ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "SN002",
    type: "alert",
    icon: "🔴",
    title: "Low Attendance Warning",
    desc: "Your attendance in Computer Networks has dropped to 70%. You need 4 more classes to reach 75%.",
    time: "20m ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "SN003",
    type: "session",
    icon: "🚀",
    title: "New Attendance Session Available",
    desc: "Dr. Neha Kapoor has started an attendance session for DBMS. Join before it expires.",
    time: "35m ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "SN004",
    type: "qr",
    icon: "📵",
    title: "QR Scan Failed",
    desc: "Your QR scan for Operating Systems session GA-102 failed — the code had expired. Ask your teacher to refresh it.",
    time: "1h ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "SN005",
    type: "location",
    icon: "📍",
    title: "Location Verification Failed",
    desc: "You were 82m from the classroom during DBMS session GA-101 (limit: 50m). Attendance was not recorded.",
    time: "2h ago",
    date: "Today",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN006",
    type: "announcement",
    icon: "📢",
    title: "Faculty Announcement",
    desc: 'Prof. Arjun Rao: "Operating Systems mid-semester test rescheduled to July 10th at 10 AM. Please prepare chapters 4–7."',
    time: "3h ago",
    date: "Today",
    read: false,
    category: "Announcements",
  },
  {
    id: "SN007",
    type: "session",
    icon: "🏁",
    title: "Attendance Session Closed",
    desc: "The Software Engineering session GA-104 has been closed by your teacher. Your attendance was recorded.",
    time: "4h ago",
    date: "Today",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN008",
    type: "system",
    icon: "🔧",
    title: "System Update",
    desc: "GeoAttend has been updated to v2.4.1. QR scanning is now faster and more accurate.",
    time: "5h ago",
    date: "Today",
    read: true,
    category: "System",
  },
  {
    id: "SN009",
    type: "absent",
    icon: "🔴",
    title: "Attendance Missed",
    desc: "You missed the Computer Networks session GA-103 on June 30. This is your 3rd absence in this subject.",
    time: "6h ago",
    date: "Today",
    read: false,
    category: "Attendance",
  },
  {
    id: "SN010",
    type: "achievement",
    icon: "🏆",
    title: "Achievement Unlocked!",
    desc: '🔥 You just earned the "10-Day Streak" badge. You have attended class 10 consecutive days!',
    time: "1d ago",
    date: "Yesterday",
    read: true,
    category: "Announcements",
  },
  {
    id: "SN011",
    type: "attendance",
    icon: "✅",
    title: "Attendance Marked Successfully",
    desc: "Your attendance for Operating Systems (GA-102) has been verified. Session duration: 1 hour.",
    time: "1d ago",
    date: "Yesterday",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN012",
    type: "announcement",
    icon: "📝",
    title: "Assignment Reminder",
    desc: "Software Engineering Project Phase 2 submission deadline is July 7th. Upload via the college portal.",
    time: "1d ago",
    date: "Yesterday",
    read: false,
    category: "Announcements",
  },
  {
    id: "SN013",
    type: "alert",
    icon: "⚠️",
    title: "Low Attendance Warning",
    desc: "Your overall attendance has dipped to 86%. Maintain regular attendance to avoid academic impact.",
    time: "1d ago",
    date: "Yesterday",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN014",
    type: "session",
    icon: "🚀",
    title: "New Session — Data Structures",
    desc: "Dr. Priya Mehta has opened an attendance session for Data Structures. Scan the QR code within 15 minutes.",
    time: "2d ago",
    date: "Jun 28",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN015",
    type: "announcement",
    icon: "🎓",
    title: "Examination Schedule Released",
    desc: "End semester exam timetable for November 2026 is now available on the student portal.",
    time: "2d ago",
    date: "Jun 28",
    read: true,
    category: "Announcements",
  },
  {
    id: "SN016",
    type: "system",
    icon: "🔔",
    title: "Weekly Attendance Summary",
    desc: "This week you attended 14/15 sessions (93%). Great job! Computer Networks is your only concern.",
    time: "2d ago",
    date: "Jun 28",
    read: true,
    category: "System",
  },
  {
    id: "SN017",
    type: "announcement",
    icon: "🌐",
    title: "Holiday Notice",
    desc: "College will be closed on July 4th (Friday) for the Foundation Day celebration. No classes scheduled.",
    time: "3d ago",
    date: "Jun 27",
    read: true,
    category: "Announcements",
  },
  {
    id: "SN018",
    type: "attendance",
    icon: "✅",
    title: "Attendance Marked Successfully",
    desc: "Web Development Lab (GA-105) attendance confirmed. Your current attendance in this subject: 89%.",
    time: "3d ago",
    date: "Jun 27",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN019",
    type: "session",
    icon: "⏰",
    title: "Session Expiring Soon",
    desc: "DBMS attendance session GA-101 expires in 5 minutes. Scan the QR code now if you haven't already.",
    time: "3d ago",
    date: "Jun 27",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN020",
    type: "alert",
    icon: "📉",
    title: "Attendance Risk Alert",
    desc: "Missing 2 more Computer Networks classes will bring you below the 65% threshold. Take action now.",
    time: "4d ago",
    date: "Jun 26",
    read: false,
    category: "Attendance",
  },
  {
    id: "SN021",
    type: "announcement",
    icon: "📢",
    title: "Faculty Announcement — Networks",
    desc: 'Dr. Sana Iyer: "Remedial class for Computer Networks scheduled this Saturday, 10 AM, Lab 3. Attendance mandatory."',
    time: "4d ago",
    date: "Jun 26",
    read: true,
    category: "Announcements",
  },
  {
    id: "SN022",
    type: "achievement",
    icon: "⭐",
    title: "Perfect Week Badge!",
    desc: 'You attended all 5 sessions this week. You\'ve earned the "Perfect Week" achievement!',
    time: "4d ago",
    date: "Jun 26",
    read: true,
    category: "Announcements",
  },
  {
    id: "SN023",
    type: "system",
    icon: "🛡️",
    title: "Security Notice",
    desc: "Your GeoAttend account was accessed from a new device. If this was not you, change your password immediately.",
    time: "5d ago",
    date: "Jun 25",
    read: false,
    category: "System",
  },
  {
    id: "SN024",
    type: "attendance",
    icon: "✅",
    title: "Attendance Marked Successfully",
    desc: "Your attendance for Data Structures (GA-106) is confirmed. Streak: 10 days and counting!",
    time: "5d ago",
    date: "Jun 25",
    read: true,
    category: "Attendance",
  },
  {
    id: "SN025",
    type: "announcement",
    icon: "💬",
    title: "Student Feedback Survey",
    desc: "Please complete the Mid-Semester Student Feedback Survey for all subjects by July 5th.",
    time: "6d ago",
    date: "Jun 24",
    read: true,
    category: "Announcements",
  },
];

export const STUDENT_CATEGORY_FILTERS = [
  "All",
  "Unread",
  "Read",
  "Attendance",
  "Announcements",
  "System",
];
